version: 2.1
jobs:
  test:
    docker:
    - image: okteto/golang-ci:1.17.3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 35:5c:eb:56:b5:3c:ba:f8:19:ba:54:0e:93:d9:e9:56
            # - 55:9f:e5:b2:55:9f:db:bf:42:7d:26:4d:2f:1f:63:8b
      - deploy:
          name: test
          command: |
            go get -u github.com/tcnksm/ghr
            ./update.sh 0.1.1
workflows:
  version: 2
  test:
    jobs:
      - test:
        filters:
          tags:
            only: /^\d+\.\d+\.\d+$/
          branches:
            ignore: /.*/